#!/usr/bin/env python3
"""Generate panic stubs for symbols the PC link cannot resolve.

Every unresolved symbol gets a stub that panics if it is ever actually
reached. The executable links, boots, and tells you exactly which missing
function it hit, rather than failing to build at all.

The stubs are typeless on purpose, the real signatures are unknown here, and
a stub that is called has already lost. Each is emitted as a no-argument
function, calls through a mismatched signature are fine on every ABI we target
because the stub never returns.

Usage:
    cmake --build <dir> --target melee_pc 2>&1 | python tools/gen_undefined_stubs.py
    cmake --build <dir> --target melee_pc          # links this time
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path

NEVER_STUB = {"OSPanic", "OSReport", "OSVReport", "abort"}

PATTERNS = [
    re.compile(r"undefined reference to [`'\"]([A-Za-z_][A-Za-z0-9_]*)"),
    re.compile(r"undefined symbol:?\s+([A-Za-z_][A-Za-z0-9_]*)"),
]

def defined_symbols(objdir: Path) -> set[str]:
    """Symbols with a definition somewhere in the build.

    These must never be stubbed. A generated stub is a strong definition, so it
    outranks an archive member and would silently replace a working function
    with a panic -- the linker reporting it undefined usually means a link
    *order* problem, not a missing implementation.
    """
    defined: set[str] = set()
    files = [str(p) for p in objdir.rglob("*.a")]
    files += [str(p) for p in objdir.rglob("*.o")
              if p.name != "undefined_stubs.c.o"]
    for i in range(0, len(files), 256):
        out = subprocess.run(["nm", "--defined-only", *files[i : i + 256]],
                             capture_output=True, text=True).stdout
        for line in out.splitlines():
            parts = line.split()
            # nm spells global symbols with an uppercase type letter and local
            # ones lowercase. Only a global definition can satisfy an external
            # reference -- `static int lbl_x;` in one TU cannot resolve another
            # TU's use of it, and treating it as defined would wrongly suppress
            # the stub and leave the link broken.
            if len(parts) >= 3 and parts[1].isupper():
                defined.add(parts[2])
    return defined


def classify(objdir: Path) -> set[str]:
    """Return the symbols that are *called*, by inspecting relocations.

    A symbol referenced through R_X86_64_PLT32 is the target of a call, so a
    function stub is right. Anything else is a data reference, and emitting a
    function for it means code that writes to the symbol writes into the text
    segment -- a segfault with no diagnostic, which is exactly what happened
    with HSD_Synth_804D6018.
    """
    called: set[str] = set()
    objs = [str(p) for p in objdir.rglob("*.o")]
    if not objs:
        return called
    for i in range(0, len(objs), 256):
        out = subprocess.run(["objdump", "-r", *objs[i : i + 256]],
                             capture_output=True, text=True).stdout
        for line in out.splitlines():
            if "R_X86_64_PLT32" in line:
                parts = line.split()
                if len(parts) >= 3:
                    called.add(parts[2].split("-")[0].split("+")[0])
    return called


HEADER = """// Generated by tools/gen_undefined_stubs.py -- do not edit, do not commit.
//
// One panic stub per symbol the PC link could not resolve. Reaching any of
// these means the game called into a function that is either excluded from the
// PC build or not yet decompiled.

// Implemented in melee_compat/src/misc_stubs.c. Panics by default; set
// MELEE_PC_STUB_CONTINUE=1 to log and return instead, which is how you find
// out how many of these sit between here and the next milestone rather than
// discovering them one crash at a time.
void melee_pc_missing(const char* name);

"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("-o", "--output", type=Path, required=True,
                    help="C file to write")
    ap.add_argument("input", nargs="?", type=argparse.FileType("r"),
                    default=sys.stdin, help="linker output (default: stdin)")
    ap.add_argument("--objdir", type=Path,
                    help="build dir to scan for relocations, to tell data "
                         "symbols from functions. Defaults to the output "
                         "file's directory, which is where the objects are.")
    args = ap.parse_args()

    # Without this scan every symbol is stubbed as a function, and any code
    # that *writes* one then stores into the text segment and segfaults with no
    # diagnostic. The output always lands in the build directory, so default to
    # it rather than depending on the caller remembering the flag.
    if args.objdir is None:
        args.objdir = args.output.parent

    symbols: set[str] = set()
    for line in args.input:
        for pat in PATTERNS:
            m = pat.search(line)
            if m:
                sym = m.group(1)
                if sym not in NEVER_STUB:
                    symbols.add(sym)

    if args.objdir:
        already = defined_symbols(args.objdir) & symbols
        if already:
            print(f"warning: {len(already)} symbol(s) are defined in the build "
                  f"but were reported undefined -- link order problem, not "
                  f"stubbing them: {', '.join(sorted(already)[:5])}"
                  f"{' ...' if len(already) > 5 else ''}", file=sys.stderr)
            symbols -= already

    called = classify(args.objdir) if args.objdir else symbols
    if args.objdir and not called:
        print(f"warning: no relocations found under {args.objdir}, so data "
              f"symbols cannot be told from functions; stubbing everything as "
              f"a function. Writes to a data symbol will segfault.",
              file=sys.stderr)
        called = symbols

    out = [HEADER]
    n_data = 0
    for sym in sorted(symbols):
        if sym in called:
            out.append(f'void {sym}(void);\n'
                       f'void {sym}(void) {{ melee_pc_missing("{sym}"); }}\n\n')
        else:
            # Data. Size is unknowable from here, so reserve generously and
            # zero it. Unlike the function stubs this is silent -- code that
            # reads it just sees zeroes.
            n_data += 1
            out.append(f'char {sym}[4096];\n')
    if n_data:
        out.append(f"\n// {n_data} of the above are data symbols.\n")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("".join(out), encoding="utf-8")
    print(f"{len(symbols)} stubs ({len(symbols) - n_data} functions, "
          f"{n_data} data) -> {args.output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
