// Generated by tools/gen_dat_layouts.py -- do not edit.
//
// Type ids for MELEE_PC_DAT(). Public so the HSD_*LoadDesc entry
// points can name the type they are converting; naming a type that
// is not described is then a compile error rather than a surprise.

#ifndef MELEE_PC_DAT_TYPES_H
#define MELEE_PC_DAT_TYPES_H

typedef enum {
    DAT_T_NONE = -1,
    DAT_T_HSD_Joint = 0,
    DAT_T_HSD_DObjDesc = 1,
    DAT_T_HSD_PObjDesc = 2,
    DAT_T_HSD_MObjDesc = 3,
    DAT_T_HSD_TObjDesc = 4,
    DAT_T_HSD_TlutDesc = 5,
    DAT_T_HSD_TObjTevDesc = 6,
    DAT_T_HSD_AObjDesc = 7,
    DAT_T_HSD_FObjDesc = 8,
    DAT_T_HSD_RObjDesc = 9,
    DAT_T_HSD_WObjDesc = 10,
    DAT_T_HSD_CObjDesc = 11,
    DAT_T_HSD_LightDesc = 12,
    DAT_T_HSD_FogDesc = 13,
    DAT_T_HSD_FogAdjDesc = 14,
    DAT_T_SceneDesc = 15,
    DAT_T_HSD_VtxDescList = 16,
    DAT_T_HSD_TexAnim = 17,
    DAT_T_HSD_SList = 18,
    DAT_T_HSD_LightAttn = 19,
    DAT_T_DynamicModelDesc = 20,
    DAT_T_SceneCameraDesc = 21,
    DAT_T_SceneFogDesc = 22,
    DAT_T_LightList = 23,
    DAT_T_HSD_AnimJoint = 24,
    DAT_T_HSD_MatAnimJoint = 25,
    DAT_T_HSD_ShapeAnimJoint = 26,
    DAT_T_HSD_CameraAnim = 27,
    DAT_T_HSD_LightAnim = 28,
    DAT_T_HSD_WObjAnim = 29,
    DAT_T_HSD_RObjAnimJoint = 30,
    DAT_T_HSD_MatAnim = 31,
    DAT_T_HSD_RenderAnim = 32,
    DAT_T_HSD_ChanAnim = 33,
    DAT_T_HSD_TevRegAnim = 34,
    DAT_T_HSD_ShapeAnim = 35,
    DAT_T_HSD_ShapeAnimDObj = 36,
    DAT_T_HSD_Material = 37,
    DAT_T_HSD_RvalueList = 38,
    DAT_T_Vec = 39,
    DAT_T_HSD_ShapeSetDesc = 40,
    DAT_T_HSD_EnvelopeDesc = 41,
    DAT_T_HSD_PEDesc = 42,
    DAT_T_HSD_ImageDesc = 43,
    DAT_T_HSD_TexLODDesc = 44,
    DAT_T_HSD_ExpDesc = 45,
    DAT_T_HSD_ByteCodeExpDesc = 46,
    DAT_T_HSD_IKHintDesc = 47,
    DAT_T_HSD_LightPointDesc = 48,
    DAT_T_HSD_LightSpotDesc = 49,
    DAT_T_COUNT = 50
} DatTypeId;

#endif
